### ISSUE TITLE
Create.go doesn't reference new /v2 lib

### ISSUE THREAD

**Issue by bennichols** [robinjoseph08/go-pg-migrations#17]
The template on line 16 still says `migrations "github.com/robinjoseph08/go-pg-migrations"` when it should read `migrations "github.com/robinjoseph08/go-pg-migrations/v2"`

**Comment by robinjoseph08** [comment]
Ah apologies for that! I'll get the fix merged in and cut a new version.

**Comment by robinjoseph08** [comment]
Fixed by #18 and v2.0.1 has been pushed with the fix. Thanks again!
