### ISSUE TITLE
Revert only last migration

### ISSUE THREAD

**Issue by ahanoff** [robinjoseph08/go-pg-migrations#20]
Is it possible to revert only last migration? 🤔

**Comment by robinjoseph08** [comment]
Hey @ahanoff, sorry for the delay!

There currently isn't a way to revert an individual migration. Each call to `rollback` will rollback an entire "batch", where a batch is all of the migrations that are run together. For example, if I write 3 migrations and then deploy/run `migrate`, all 3 migrations will be in the same batch. So if I then run `rollback`, it will rollback all 3 of them. If the intention is to always be able to rollback individual migrations, they should be deployed and run individually.

Hope that makes sense! If not, feel free to reopen!
