### ISSUE TITLE
Seems to be incompatible with github.com/go-pg/pg/v10

### ISSUE THREAD

**Issue by ernsheong** [robinjoseph08/go-pg-migrations#22]
Current release seems to be incompatible with github.com/go-pg/pg/v10

**Comment by ernsheong** [comment]
Same behavior in other repo https://github.com/go-pg/migrations, looks like no harm just installing v9 to run migrations.

**Comment by robinjoseph08** [comment]
@ernsheong Thanks for the heads up! While it's possible to make it work by just using `v9`, I do think it's better to use the latest version to get bug fixes and to be more future-looking. I'll go ahead and reopen this issue so that we're tracking the need to update.

**Comment by robinjoseph08** [comment]
I was just about to update it, but it looks like v10 is currently on alpha.0. I've got the branch ready to go, but I'll wait until it's stable to merge it into master and create a v3.

**Comment by kimrgrey** [comment]
@robinjoseph08 I think v10 is the default branch now. Can we update migrations to use it by default as well? Thanks!

**Comment by lsnow99** [comment]
Bump

**Comment by robinjoseph08** [comment]
Apologies for the delay here. I've cleaned up my branch and have pushed it up. Once the build passes, I'll merge and release v3.0.0.

**Comment by robinjoseph08** [comment]
Just released v3.0.0!

**Comment by ernsheong** [comment]
Thanks Robin
